### ISSUE TITLE
server.py will only run once

### ISSUE THREAD

**Issue by razzamatazm** [blawar/nut#108]
I can run server.py and it will scan and serve just fine. But only once. When I close it and reopen it, it locks up upon trying to scan again. This is repeatable for me - and it happens with 1.2 and 1.1 and the exe file. I can fix by removing everything and extracting again.

Any ideas?

**Comment by plato79** [comment]
Do you have a big archive? Because it really doesn't lock up.. It just reads everything at once, and writes the content after that.. I checked the code myself and saw no async reads.. I think JS code needs optimization. While I know how to do certain things I'm not very experienced on JS. So if anyone have the time, please check the code and think about how to optimize the code.

It takes about 45 seconds to get the page with all the titles..

**Comment by razzamatazm** [comment]
I’ve let it sit for hours and it just hangs.

**Comment by plato79** [comment]
So, there's also nothing going on with command line? You should have seen server started at 0.0.0.0:9000 or something ( I cannot remember full message ). If you can't then yes, definitely something is wrong with Python side of the code, and it's a bit difficult to find out where it's stuck. 

After the server is started HTML+JS side of the code runs and it's a bit easier to debug that side of the code with Chrome.

**Comment by throwawayay** [comment]
Need stack trace; make sure to follow (updated) readme
