### ISSUE TITLE
[Bug] QtRAngeSLider???

### ISSUE THREAD

**Issue by ungentilgarcon** [blawar/nut#300]
Used to work, now returns:

filters.py", line 5, in <module>
    from qt_range_slider import QtRangeSlider
ModuleNotFoundError: No module named 'qt_range_slider'

on debian

**Comment by introkun** [comment]
try
`pip3 install -r requirements.txt`

**Comment by krissZero** [comment]
Hello, same trouble. After using requirement.txt, error apear about pillow. 
"failled building  wheel  for pillow"

python setup.py bdist_wheel did not run successfully

So i upgrade pip and pillow manual with pip, installation was successfull of pillow. but after that, when i run python3 nut_gui.py i have the error describe before (qt_range_slider)

Is it because i have installed pillow manually ? There is a solution to run requiretement.txt without error ? 

I am with debian 12

Thx and regards

**Comment by krissZero** [comment]
Error during execution of nut_gui.py

Traceback (most recent call last):
  File "/home/kriss/Documents/nut/nut_gui.py", line 13, in <module>
    from gui.app import App
  File "/home/kriss/Documents/nut/gui/app.py", line 12, in <module>
    import gui.panes.filters
  File "/home/kriss/Documents/nut/gui/panes/filters.py", line 5, in <module>
    from qt_range_slider import QtRangeSlider
ModuleNotFoundError: No module named 'qt_range_slider'

**Comment by MarioFromTheFH** [comment]
I came here with the same question. No proper solution online, but strangely this package exists and also works:

`$ pip install qt_range_slider`
